### ISSUE TITLE
check-disk-usage plugin failing

### ISSUE THREAD

**Issue by sputturao** [sensu-plugins/sensu-plugins-disk-checks#31]
Tried to use the check-disk-usage plugin and fails.

[root@izscalrdevwork1 plugins]# /opt/sensu/embedded/bin/ruby check-disk-usage.rb
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sys/filesystem (LoadError)
        from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from check-disk-usage.rb:29:in `<main>'

Before using this plugin, we used to use the old community plugin and that worked without any issue.
Old Plugin: https://github.com/sensu/sensu-community-plugins/blob/master/plugins/system/check-disk.rb 

[root@izscalrdevwork1 plugins]# /opt/sensu/embedded/bin/ruby check-disk.rb
CheckDisk OK: All disk usage under 85% and inode usage under 85%

**Comment by sputturao** [comment]
OS is Oracle Linux

**Comment by sputturao** [comment]
tried to install gem sys-filesystem and still didnt help

/opt/sensu/embedded/bin/ruby check-disk-usage.rb 
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sys/filesystem (LoadError)
	from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from check-disk-usage.rb:29:in `<main>'

**Comment by axos88** [comment]
+1

**Comment by willneumob** [comment]
+1

**Comment by eheydrick** [comment]
@willneumob @axos88 which OS are you seeing this on?

**Comment by willneumob** [comment]
This is freshly-installed Ubuntu 14.04.3 LTS with ruby and ruby-dev 1.9.1, after a `gem install sensu-plugin`.

**Comment by axos88** [comment]
@willneumob sorry, no idea, that was two months ago. I moved over to the old community plugin.

**Comment by eheydrick** [comment]
I will try to repro this. It's working for me on Ubuntu 14.04 using the Sensu embedded Ruby 2.3.

**Comment by immusk** [comment]
I am facing the same issue as posted by @sputturao 
I have sensu server and client on same machine and I am using centos
When I run it through command line I am getting the correct output, but when I configured the check in json file I am getting the same above mentioned issue.

Can anyone help me to get out of this?

**Comment by agraziolo** [comment]
Hi all, I have exactly same problem mentioned by @immusk did you have any luck on finding a solution? I've tried with require_relative (in the .rb), giving permissions to execute and other things, without success. Thanks in advance if you can help me or post some used resolutions.

**Comment by lcx** [comment]
I was facing the same issue and here is my solution. 
I was testing with root and it worked, doing the same as sensu user didn't and gave me the same error as mentioned above. 
The problem is that when installing the gem, it goes to the root users .gem/ directory
You can check where the gem is installed with 

    /opt/sensu/embedded/bin/gem environment

and you will get something like this

```
  - INSTALLATION DIRECTORY: /opt/sensu/embedded/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
```

you need to install the gem in the INSTALLATION DIRECTORY and not the USER INSTALLATION DIRECTORY.

if you are using ansible to install the gem set user_install=no

```
    - name: Install sys-filesystem gem
      gem: name=sys-filesystem version=1.1.5 state=present user_install=no executable=/opt/sensu/embedded/bin/gem
```

**Comment by eheydrick** [comment]
Is this still an issue?

**Comment by fkwakkenbos** [comment]
This is solved when you specify the path of the disk to check.
Otherwise it will also check ramdisks etc, and the sensu user has no permissions to do that check.

**Comment by valenbb** [comment]
My apologies for adding to this closed issue, but the above did not help and hopefully this cal help others.

Resolved issue by downloading sys-filesystem gem and its runtime dependency (ffi-1.9.18.gem) into following location: /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems

Ran commands below:
cd /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems install --local <gems listed above>

Now this plugin works for me.

**Comment by majormoses** [comment]
I just did a release can someone try it and see if the issue is resolved, if not I will start taking a look at this issue.

**Comment by tkaczerski** [comment]
getting these failures randomly after upgrading to 2.1.0...

"Check failed to run: Permission denied - setmntent, [""/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sys-filesystem-1.1.7/lib/sys/unix/sys/filesystem.rb:301:in `mounts'"", ""/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-disk-checks-2.1.0/bin/check-disk-usage.rb:121:in `fs_mounts'"", ""/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-disk-checks-2.1.0/bin/check-disk-usage.rb:209:in `run'"", ""/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'""]",1493906868,,standard,ACTIVE

**Comment by majormoses** [comment]
@tkaczerski sorry to hear, can you give me your full command being run?

**Comment by tkaczerski** [comment]
/opt/sensu/embedded/bin/check-disk-usage.rb -w 86 -c 93

The issue could be: 
[https://github.com/sensu/sensu-omnibus/issues/179](url)

**Comment by tkaczerski** [comment]
All issues resolved after upgrading glibc.

**Comment by majormoses** [comment]
@tkaczerski thanks I get a 404 so I'm guessing its a private repo. Could you submit a pr to document the requirements?
