### ISSUE TITLE
Use sys-filesystem for disk metrics instead of df and /proc

### ISSUE THREAD

**Issue by mattyjones** [sensu-plugins/sensu-plugins-disk-checks#9]
the set of disk metrics plugins should use the sys-filesystem if possible instead of arch specific tools such as df output or /proc.

**Comment by rmc3** [comment]
Tested check-disk-usage.rb on Windows Server 2008. It fails with the following output:

```
PS > ruby.exe .\bin\check-disk-usage.rb
Check failed to run: nil can't be coerced into Float, ["./bin/check-disk-usage.rb:117:in `*'", "./bin/check-disk-usage.rb:117:in `percent_inodes'", "./bin/check-disk-usage.rb:101:in `block in fs_mounts'", "./bin/check-disk-usage.rb:91:in `each'", "./bin/check-disk-usage.rb:91:in `fs_mounts'", "./bin/check-disk-usage.rb:135:in `run'", "C:/contegix/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

The cause appears to be that the struct returned by sys-filesystem on Windows does not include the ```:inodes``` and ```:inodes_free``` fields. It might be simplest to just skip the inodes logic if ```!@fs_info.respond_to?(:inodes) or !@fs_info.respond_to?(:inodes_free)```

**Comment by mattyjones** [comment]
fair enough, if you want to PR it go ahead, if not I will do it when I get a few minutes at some point.

Thanks!

**Comment by mattyjones** [comment]
@rmc3 

I finally circled around to this and incorporated your above suggestion, thanks for checking on this for me.

**Comment by majormoses** [comment]
@mattyjones can this be closed?

**Comment by majormoses** [comment]
closing due to inactivity
